name: Publish Extension

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install webview dependencies
        run: npm ci
        working-directory: webview

      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish -p "$VSCE_PAT"
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
